### ISSUE TITLE
Jest detecting open handle

### ISSUE THREAD

**Issue by robross0606** [echo-health/koa-prometheus-exporter#22]
Jest is reporting that @echo-health/koa-prometheus-exporter has a handle left open after tests:
```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  nan:test.DelayRequest

      11 | const OpentracingExtension = require('apollo-opentracing').default
      12 | const { initTracer /*, initTracerFromEnv, PrometheusMetricsFactory*/ } = require('jaeger-client')
    > 13 | const prometheus = require('@echo-health/koa-prometheus-exporter')
         |                    ^
      14 | const opentracing = require('opentracing')
      15 | 
      16 | const config = require('./config')

      at gcStats (node_modules/gc-stats/index.js:17:13)
      at node_modules/prometheus-gc-stats/index.js:56:7
      at Object.<anonymous> (node_modules/@echo-health/koa-prometheus-exporter/src/index.js:3:48)
      at Object.<anonymous> (src/server.js:13:20)

Waiting for the debugger to disconnect...
```

**Comment by robross0606** [comment]
From what I can tell, this is being caused by the index.js of the module calling `client.collectDefaultMetrics()`.  This in turn calls `setInterval()`.  So the code is kicking off a recurring timer just by requiring the module.  The handle for the timer is never returned so there's no way to control it from outside the module.  This is an anti-pattern.  Instead, export some way for the user to control when (if?) they want to start this timer and provide the handle for the timer back to the user.
